const entriesCsv = `id,title,category,subtitle,lead,img1,img2,img3,img4,x,y,body
4,‘Blokjeskaart’,2,BEROEMD SYMBOOL VAN TRADITIE VAN LANGE TERMIJN PLANNING,Leg deze kaart uit 1966 naast Nederland nu en zie hoe visionair de plannenmakers zijn geweest.,true,true,false,false,0,0,"De Toelichtingskaart nr. 3 bij de Tweede Nota over de ruimtelijke ordening in Nederland (1966), bekend geworden als de ‘Blokjeskaart’, is een kaart die nog steeds van invloed is. Een voorbeeldig planinstrument, maar ook kenmerkend voor het doorgeschoten maakbaarheidsdenken in de jaren zestig.
De gele, oranje, rode en bruine blokjes staan voor vier typen verstedelijking. Deze milieudifferentiatie duidde aan hoe in het jaar 2000 twintig miljoen inwoners gehuisvest zouden kunnen worden in uiteenlopende woonmilieus, van dorpse milieus zoals in Paterswolde tot hoogstedelijk zoals in Amsterdam-Centrum. De woongebieden moesten, over het land verspreid, zoveel mogelijk gebundeld worden in stadsgewesten (→ 5).
De vorm van de kaart was vernieuwend en de onderliggende ideeën van milieudifferentiatie en stadsgewesten waren invloedrijk. De kaart werd bij de Rijksplanologische Dienst gemaakt door Eo Wijers en Götz Nassuth.
Opvallend veel van de nieuwe kernen zijn moeiteloos op de kaart van nu terug te vinden en vormen vaak gewilde woonmilieus: Almere (→ 2), Blaricum, Huizen en Zoetermeer bijvoorbeeld.
Al was hun vorm schematisch, de oppervlakte van de blokjes stond voor de reële oppervlakte en elk type had een uitgesproken karakteristiek, met 15 tot 60 woningen per hectare. Type A (geel) stond voor een ruimtelijke eenheid binnen het stadsgewest van om en nabij 5.000 inwoners, met streekbus, plantsoen en wijkwinkel – vergelijkbaar met Paterswolde, Breukelen en Aerdenhout. De andere types (met resp. 15.000, 60.000 en 250.000 inwoners) werden bedacht met een stoptrein, stadsbus of exprestrein. Die laatste deed alleen de grootste kernen aan en alleen daar waren gespecialiseerde winkels te vinden zoals ‘bontwinkel of broekenpaleis’.
Verschil tussen de Blokjeskaart en huidige realiteit is vooral de mate waarin de grootste provinciale steden gegroeid zijn. Groningen, Leeuwarden, Twente, Zuid-Limburg (→ 24), Tilburg en Breda zijn minder groot geworden dan op de kaart van 1966 was voorzien.
‘Grote Nota’s’ zoals de Tweede Nota zijn karakteristiek voor de Nederlandse traditie van ruimtelijke ordening. Sindsdien hee het Rijk nog vier van dergelijke nota’s uitgebracht die bepalend zijn voor de ruimtelijke ordening op nationaal schaalniveau."
9,Ecologische Hoofdstructuur,3,DE OPBOUW VAN EEN ECOLOGISCHE HOOFDSTRUCTUUR,Dertig jaar lang natuurgebieden aaneenrijgen tot planten en dieren de ruimte hebben om te overleven.,Ecoduct Best,true,"Moerasgebied Botshol, een beschermd natuurgebied in de provincie Utrecht (gemeente De Ronde Venen). ",false,0,0,"De Ecologische Hoofdstructuur (EHS) is een samenhangend netwerk van belangrijke bestaande en nog te ontwikkelen natuurgebieden in Nederland (→ 15). De EHS stamt uit 1990, als strategisch concept uit het Natuurbeleidsplan van het Ministerie van LNV, en bood inspiratie aan het Europese Natura 2000 project. Dat verbindt op Europese schaal natuurgebieden aan elkaar. In Nederland zijn de meeste Natura 2000-gebieden onderdeel van de EHS.
De EHS vormt de basis voor het Nederlandse natuurbeleid, dat tot doel hee de achteruitgang van de biodiversiteit een halt toe te roepen.
De EHS is opgebouwd uit kerngebieden, natuurontwikkelingsgebieden en verbindingszones. In elk EHS-gebied wordt toegewerkt naar specifiek omschreven natuurdoelen. Het streven was om in 2020 meer dan 750.000 hectare aan ‘droge’ EHS-gebieden te hebben (ruim 17% van het Nederlandse landoppervlak) maar is nu naar beneden bijgesteld. Daarnaast vallen grote delen van de Waddenzee, IJsselmeer en andere waterrijke gebieden onder de ‘na e’ EHS.
In het algemeen leidt de aanleg van grootschalige infrastructuur tot versnippering van natuurgebieden, wat problemen geeft voor de verspreiding en instandhouding van veel diersoorten. In een aantal gevallen is aanleg nodig van nieuwe infrastructuur (ecoducten) ter verbinding van gescheiden natuurgebieden. Eerste voorbeeld van de speciale infrastructuur die de EHS vergt om voorheen gescheiden natuurgebieden te verbinden is het wildviaduct bij Terlet. Het werd in 1990 gebouwd over de snelweg A50 ten noorden van Arnhem als een oversteekplaats voor dieren: een speciaal ontworpen ‘wildwissel’ voor de natuur. De foto toont een recent ecoduct over de A2 bij Best, ten noorden van Eindhoven.
De aanwijzing van beschermde natuurgebieden, met name de stringente Natura 2000-gebieden, heeft consequenties voor de ruimtelijke ordening. Regelmatig leidt dit tot maatschappelijke commotie. De aanleg van de Maasvlakte bij de Rotterdamse haven (→ 28), IJburg bij Amsterdam en de uitdieping van de Westerschelde zijn voorbeelden waar ruimtelijke projecten door natuurbescherming niet of anders uitgevoerd worden.
Een veel toegepast principe is dat van natuurcompensatie. De aanleg van een nieuw natuurgebied compenseert elders aangerichte schade aan de natuur, zoals de verplaatsing van een mosselbank bij IJburg illustreert. Ook dat is niet onomstreden: sommigen vinden dit potsierlijk geschuif met natuur.
Naast gebiedsbescherming kent het natuurbeleid nog soortenbescherming; ook die regelgeving kan bouwplannen behoorlijk beïnvloeden. Daar zijn zeldzame diersoorten zoals korenwolf (→ 33) en kamsalamander beroemd en berucht door geworden."
10,Groeikern Houten,2,GROEIKERNEN IN PLAATS VAN EEN HUIZENZEE,"Van 3 miljoen woningen midden jaren zestig naar 7 miljoen nu, is met groeikernen in goede banen geleid.",Houten,Grote steden (rood) en groeikernen (wit),Houten,false,5.16083,52.02838,"In de Tweede Nota over de Ruimtelijke Ordening in Nederland (1966) wordt een aantal plaatsen aangewezen die als ‘overloop’ moeten dienen voor de steden in de Randstad (→ 4, 1). Men vreesde dat anders Amsterdam, Rotterdam en Den Haag tot onbeheersbare metropolen zouden uitgroeien. Onbeheersbaar omdat alles zou vastlopen (congestie), maar ook omdat ongebreidelde woningbouw in het groen rond de steden dreigde (suburbanisatie) (→ 21). Daarnaast voorzag men een tekort aan arbeidskrachten als alle bedrijvigheid zich in het Westen zou concentreren. Spreiding van werkgelegenheid was daarom gewenst, mede omdat in de landelijke gebieden werkgelegenheid in de agrarische sector afnam.
De plaatsen die deze overloop in gebundelde vorm moesten opvangen zijn bijvoorbeeld Houten, Alkmaar, Purmerend, Lelystad (→ 2), Roca (Rotterdam Oost + Capelle aan den IJssel) en de dan nog nieuw te bouwen polderstad Almere. In het zuidelijk deel van de Randstad moesten Zoetermeer, Hellevoetsluis, Dordrecht en Breda de overloop opvangen.
Het woord ‘groeikern’ doet pas in de Derde Nota (Verstedelijkingsnota, 1976) zijn intrede, maar deze groeikernen waren voor een groot deel dezelfde plaatsen als de eerdere overloopgemeenten. Hoorn wordt toegevoegd, Dordrecht verdwijnt. Daarnaast worden Groningen, Zwolle en Breda tot ‘groeistad’ bestemd.
Zo is de groei in Nederland, van 3 miljoen woningen midden jaren zestig naar 7 miljoen nu, in goede banen geleid.
Over kwaliteit is natuurlijk altijd te twisten, niet alle groeikernen zijn even geslaagd. Een goed voorbeeld is Houten, met name omdat het stedenbouwkundig ontwerp hier aantoonbaar hee bijgedragen aan minder autogebruik en meer gebruik van ets en openbaar vervoer (→ 34) dan in vergelijkbare gevallen."
13,IJsselmeerpolders,1,LANDAANWINNING EN INPOLDERING,"Als we ruimte tekort komen, maken we het bij - met polders en landaanwinningen in zee.",Wieringermeer,true,Noordoostpolder,Afsluitdijk,5.58003,52.4736,"Typerend voor de Nederlandse ruimtelijke ordening is dat, als men meent ruimte tekort te komen, die ruimte er eenvoudigweg bijgefantaseerd wordt en in vele gevallen ook daadwerkelijk gemaakt. Van alle inpolderingen is de bekendste de door de Unesco als werelderfgoed beschermde Beemster in Noord-Holland (drooggelegd tussen 1607 en 1612). De negentiende-eeuwse Haarlemmermeerpolder, waarin Schiphol is gelegen, is de grootste in zijn soort.
Maar nog meer tot de verbeelding spreekt de landaanwinning in de voormalige Zuiderzee: de IJsselmeerpolders. Daaraan is onverbrekelijk de naam verbonden van Cornelis Lely (1854-1929), ingenieur en tussen 1891 en 1918 in drie verschillende kabinetten minister van Waterstaat, Handel en Nijverheid (→ 14). Toen hij op 36-jarige leeftijd minister werd had hij net zijn plan voltooid voor afsluiting en inpoldering van de Zuiderzee, gemaakt in dienst van de Zuiderzeevereniging die zich de inpoldering als doel had gesteld. Hoewel destijds al zeer lang gesproken werd over inpoldering van deze zee, was Lely de eerste die een technisch uitvoerbaar plan presenteerde. Lely’s plan gaf antwoord op problemen zoals de afwatering van de IJssel. Ook bij zijn plan is lang gediscussieerd over vooren nadelen zoals de economische gevolgen voor vissersdorpen, de prijs van het project en de risico’s.
De doorslag om tot uitvoering over te gaan was gebrek aan voedsel tijdens de Eerste Wereldoorlog (→ 22). Om als land zelfvoorzienend te kunnen zijn moest er extra landbouwgrond komen. Ook de watersnood van 1916 droeg bij aan de omslag in denken. In 1918 loodste minister Lely de Zuiderzeewet door het parlement. Zijn plan hield een aanzienlijke verkorting in van de kustlijn, dankzij de 30 km lange Afsluitdijk – een dijk die in zijn pure eenvoud nog steeds tot de verbeelding spreekt.
De eerste inpoldering was die van de Wieringermeer in 1930. Voortbouwend op de goede ervaringen daarmee startte de inpoldering van de Noordoostpolder in 1936. Later volgden de twee Flevopolders. waarbij zuidelijk Flevoland een belangrijke opvangtaak kreeg voor de groeiende woningbehoefte van de Noordvleugel van de Randstad, met name in de nieuwe stad Almere (→ 4).
Aan het ontwerp van de polders is af te lezen dat in de Nederlandse ruimtelijke ordening de kwaliteit van het ontwerp altijd een belangrijke rol heeft gespeeld. Vooraanstaande ontwerpers als Granpré Molière, Verhagen en Van Eesteren speelden een grote rol. Vooral de inrichting van de Noordoostpolder werd een levensgroot testgebied voor Christallers centraleplaatsentheorie wat betreft omvang en onderlinge afstand van woonkernen.
De Wieringermeer en de Noordoostpolder werden drooggelegd en ingericht onder leiding van Rijkswaterstaat (→ 19) met een voornamelijk agrarische verkaveling. De Flevopolders kwamen onder de Dienst IJsselmeerpolders te vallen, waarbij stedenbouw en landschapsarchitectuur een grotere rol gingen spelen.
Overheerst in de Noordoostpolder traditionele baksteenarchitectuur, in Lelystad domineert moderne standaardisatie; Almere startte met woonerven, en wil nu proeftuin zijn voor particulier opdrachtgeverschap en duurzaamheid.
De Markerwaard staat model voor de aarzeling over verder inpolderen (→ 35). Waar zou de grond eigenlijk rendabel voor zijn: een tweede nationale luchthaven, graanproductie, woningbouw of als recreatiegebied? Slechts de helft van de dijken is aangelegd. Het ecologisch belang (→ 6) van het openhouden van het IJsselmeer prevaleerde boven de eerder genoemde mogelijke bestemmingen. Lelystad werd kind van de rekening. Van het idee dat dit de centrale stad van alle polders moest worden kwam niets terecht. Deze pas op de plaats laat onverlet dat op andere plaatsen land aanwinnen op zee doorgaat, zoals bij de Tweede Maasvlakte (→ 28). Stijging van de zeespiegel heeft ook ideeën zoals het Plan Waterman, voor landaanwinning voor de kust van Zuid-Holland, nieuw leven ingeblazen."
20,Nagele,2,DE TRADITIE VAN ZORGVULDIG ONTWERP,Symbool voor de maakbare samenleving – ook de bevolking van de IJsselmeerpolders werd gekneed.,Nagele,true,true,false,5.72182,52.644,"Te beginnen met de Wieringermeer en vervolgens de Noordoostpolder kan de inpoldering van de Zuiderzee (→ 2) gezien worden als een grote oefening in het maken van samenlevingen. Het is ook een toonbeeld van de Nederlandse traditie van zorgvuldig ontwerp. Niet alleen over de inrichting van de polders, de dorpen, stadjes en etsbare afstanden werd minutieus nagedacht, de toekomstige bewoners werden even minutieus gescreend. Traditionele normen en waarden stonden hoog in het vaandel en werden weerspiegeld in traditionele architectuur en stedenbouw.
Met die traditie werd voor het eerste gebroken in Nagele, een modern dorp in de Noordoostpolder dat tijdens de naoorlogse wederopbouw (→ 18) tot stand kwam. Het was ontworpen als modeldorp voor de stedenbouwkundige en architectonische ideeën van het Nieuwe Bouwen (→ 16), de eerste proeve van moderne architectuur op het platteland. Nagele kreeg een strak geometrisch stratenpatroon en een aparte winkelstrook. Het hart van Nagele is een uitgestrekt grasveld, in plaats van een besloten pleintje zoals in de traditionele dorpen. De strakke, open vorm van de verkaveling komt ook terug in de architectuur van de openbare gebouwen en woningen, die voor het eerst in de polder platte daken kregen in plaats van zadeldaken met dakpannen.
Zoals voor de meeste nieuwe bewoners van de Noordoostpolder gold, werden de eerste inwoners gescreend door een rijksdienst die erop toezag dat Nagele een afspiegeling van de samenleving zou vormen met inwoners van ‘goed gedrag’. De moderne architectuur kon hun hierbij een handje helpen. De keukens in de huizen waren met opzet klein om het in de keuken eten, zoals gebruikelijk was in de maatschappelijke ‘onderklasse’, te voorkomen. Net zo haaks op de wensen van de gebruikers stonden de platte daken zonder vliering of zolder waar men de ‘rotzooi’ kon bewaren.
Het sociale experiment was bij aanvang al achterhaald. Door mechanisering van de landbouw moesten landarbeiders ander werk zoeken in naburige plaatsen. Met de komst van de brommer en de auto werd de actieradius van de inwoners groter. De lokale middenstand kwijnde weg en Nagele werd geleidelijk door nieuwe inwoners bevolkt. Dit liep parallel aan de ontwikkeling in Flevoland waar een veel minder op de agrarische traditie gebaseerde samenleving groeide met bewoners die veelal uit de Randstad afkomstig waren."
26,Randstad & Groene Hart,"2,3",SCHEIDING VAN STAD EN LAND,Stad en land als mal en contramal. Basis van alle ruimtelijk beleid in Nederland. Altijd onder druk.,true,true,Zicht op Rotterdam,false,4.77962,52.19950,"De Randstad en daarbinnen het Groene Hart als contramal vormden decennialang het meest centrale en constante ruimtelijke concept in het nationale ruimtelijke beleid. Een scherpe scheiding tussen stad en land is typerend voor de Nederlandse traditie van ruimtelijke ordening. Albert Plesman, grondlegger van de KLM, typeerde in 1938 als eerste de ring van steden tussen Amsterdam, Haarlem, Leiden, Den Haag, Rotterdam, Gouda en Utrecht als Randstad. Deze indruk maakte het op hem, gezien vanuit de lucht en op de kaart.
Na 1945 werd de term Randstad gemeengoed. De Randstad is als Green Heart Metropolis – de typering komt van de Engelse planoloog Gerald Burke in 1966 – een treffend voorbeeld van bundeling (→ 5) en beperking van stedelijke groei en behoud van groene structuren. Een benadering die nu al decennialang de Nederlandse ruimtelijke ordening bepaalt.
De Randstad was en is het gebied waar bijna de helft van de Nederlanders woont, waar het zwaartepunt van werkgelegenheid en economische ontwikkeling ligt en zich het centrum van bestuur en beleid bevindt. In het rapport ‘De ontwikkeling van het Westen des Lands’ (1958) werd gevreesd voor het dichtslibben van het hele stedelijke gebied. Daarom stelde het rijk voor buffers (→ 21) tussen de steden open te houden evenals het middengebied, in combinatie met bundeling van verdere verstedelijking op een beperkt aantal plekken elders in het land. De ‘eerste’ Nota inzake de Ruimtelijke Ordening (1960) schetst een naar buiten gericht groeimodel voor de Randstad rondom het open middengebied.
Internationaal geldt de Randstad, samen met het Rijn-Ruhr gebied in Duitsland, als het archetype van de polycentrische metropool. In hoeverre de Randstad werkelijk als één stad functioneert, is echter punt van discussie. Het Ruimtelijk Planbureau relativeerde het concept in een studie met de veelzeggende titel ‘Vele steden maken nog geen Randstad’ (2006).
Het Groene Hart, de contramal van de Randstad, is markant voor openruimtebeleid maar is eerder een planologische constructie, een concept of idee, dan een geografische eenheid. Met de Hongerwinter van 1944 nog vers in het geheugen werd in de jaren vijftig besloten dit gebied zoveel mogelijk agrarisch te benutten.
Vanaf de jaren zestig verschoof het accent in het beleid richting recreatie. Onder invloed van de toenemende mobiliteit nam daarnaast de stedelijke druk op dit veenweidegebied toe; reden om een restrictief rijksbeleid te formuleren, waarbij gemeenten uitsluitend nog voor eigen inwoners mochten bouwen.
Wie de achtereenvolgende nota’s voor de ruimtelijke ordening naslaat op het formaat van het Groene Hart, ziet het open gebied steeds kleiner worden. De precieze grenzen werden voor het eerst vastgelegd in 1993. Dat neemt niet weg dat ook sindsdien aan het gebied is geknabbeld. De ruim zeven kilometer lange HSL-tunnel (→ 28) tussen Hoogmade en Hazerswoude is een opvallend compromis om het Groene Hart zoveel mogelijk open te houden. Het prijskaartje eraan maakte deze keuze omstreden."`;

export { entriesCsv };