//The dictionary keys correspond with the entry numbers in the Canon RO book

export const entryIdTransformDict = {
  10: { appId: 1, title: 'Amsterdam Zuid Berlage' },
  16: { appId: 2, title: 'AUP Amsterdam' },
  30: { appId: 3, title: 'Beekherstel Beerze Reusel' },
  4: { appId: 4, title: '‘Blokjeskaart’' },
  9: { appId: 5, title: 'Bolwerkparken van Zwolle' },
  27: { appId: 6, title: 'Céramique Maastricht' },
  23: { appId: 7, title: 'Dapperbuurt Amsterdam' },
  19: { appId: 8, title: 'Deltawerken' },
  6: { appId: 9, title: 'Ecologische Hoofdstructuur' },
  5: { appId: 10, title: 'Groeikern Houten' },
  26: { appId: 11, title: 'De Grote Karel' },
  25: { appId: 12, title: 'Haagse Beemden Breda' },
  2: { appId: 13, title: 'IJsselmeerpolders' },
  13: { appId: 14, title: 'Knooppunt Oudenrijn' },
  17: { appId: 15, title: 'Kootwijkerzand' },
  18: { appId: 16, title: 'Lijnbaan Rotterdam' },
  28: { appId: 17, title: 'Mainports Rotterdam, Schiphol' },
  21: { appId: 18, title: 'Midden-Delfland' },
  15: { appId: 19, title: 'Naardermeer' },
  3: { appId: 20, title: 'Nagele' },
  31: { appId: 21, title: 'Nederweert' },
  8: { appId: 22, title: 'Nieuwe Hollandse Waterlinie' },
  24: { appId: 23, title: 'Oostelijke mijnstreek' },
  32: { appId: 24, title: 'Paleiskwartier ‘s-Hertogenbosch' },
  7: { appId: 25, title: 'Pieterpad' },
  1: { appId: 26, title: 'Randstad & Groene Hart' },
  34: { appId: 27, title: 'Randstadrail' },
  12: { appId: 28, title: 'Rijksstraatwegenplan' },
  33: { appId: 29, title: 'Korenwolf' },
  20: { appId: 30, title: 'Stokstraat Maastricht' },
  22: { appId: 31, title: 'Tielerwaard' },
  11: { appId: 32, title: 'Tuindorp Heveadorp' },
  29: { appId: 33, title: 'VINEX Leidsche Rijn Utrecht' },
  35: { appId: 34, title: 'Waddenzee' },
  14: { appId: 35, title: 'Zuid-Willemsvaart' }
};
